Start by running the line below.

In [5]:
%run III_functions.ipynb

#### Utilities

Insert the conditional utility matrix U(row | col) here, like this:

```
U = np.array([[1,0,0],[1,0,1],[1,1,0]])
```

In [6]:
U = np.array([[1,0,0],[1,0,1],[1,1,0]])
print(U)

[[1 0 0]
 [1 0 1]
 [1 1 0]]


#### Act Probabilities

Enter the act probability distribution here, like this:
```
actprobs = np.array([1/3,1/3,1/3])
```

In [9]:
actprobs = np.array([1/3,1/3,1/3])
print(actprobs)

[0.33333333 0.33333333 0.33333333]


Check the rho-values for each of the acts (where rho(a) = max { I(a, b) | C(b) > o }) by running 
```
print(rhos(actprobs, U))
```

In [10]:
print(rhos(actprobs,U))

[0. 0. 0.]
